# Generated by Django 3.2.12 on 2023-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
