# Generated by Django 3.2.12 on 2023-09-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230927_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(to='core.Video'),
        ),
    ]
