# Generated by Django 3.2.12 on 2023-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230927_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='videos',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
