# Generated by Django 3.2.12 on 2023-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230814_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.CharField(choices=[('physik', 'Phsyik'), ('kunst', 'Kunst')], default='Phil', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.CharField(choices=[('physik', 'Phsyik'), ('kunst', 'Kunst')], default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
