# Generated by Django 4.2.7 on 2024-04-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customuser_institut_remove_profile_institut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(help_text='Eine oder mehre Videos hochladen', to='core.video'),
        ),
    ]
