# Generated by Django 3.2.12 on 2023-08-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230814_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('physik', 'Phsyik'), ('kunst', 'Kunst')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
    ]
