# Generated by Django 3.2.12 on 2023-08-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230814_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categorie',
            new_name='category',
        ),
    ]
