# Generated by Django 4.2.7 on 2024-04-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movie_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Vorschaubild für den Film -', null=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(help_text='Eine oder mehrere Videos hochladen - ', to='core.video'),
        ),
    ]
