# Generated by Django 4.2.7 on 2024-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movie_flyer_alter_movie_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
