# Generated by Django 3.2.12 on 2023-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230814_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Physik', 'Phsyik'), ('Kunst', 'Kunst')], max_length=10),
        ),
    ]
