# Generated by Django 4.2.7 on 2024-04-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_time',
        ),
    ]
