# Generated by Django 4.2.7 on 2024-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customuser_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status'),
        ),
    ]
