# Generated by Django 3.2.12 on 2023-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', '18'), ('Prof', '30')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', '18'), ('Prof', '30')], max_length=5),
        ),
    ]
