# Generated by Django 4.2.7 on 2024-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_movie_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
