# Generated by Django 3.2.12 on 2023-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230816_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], max_length=5),
        ),
    ]
