# Generated by Django 3.2.12 on 2023-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230928_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='categories',
        ),
        migrations.AddField(
            model_name='movie',
            name='group_courses',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='group_courses',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.CharField(blank=True, choices=[('Dokumentarfilm', 'Dokumentarfilm'), ('Physik', 'Physik'), ('Mathematik', 'Mathematik'), ('Informatik', 'Informatik'), ('Kunstgeschichte', 'Kunstgeschichte'), ('Chemie', 'Chemie'), ('Biologie', 'Biologie'), ('Wirtschaft', 'Wirtschaft'), ('Literatur', 'Literatur'), ('Geschichte', 'Geschichte')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_institutes',
            field=models.CharField(choices=[('IDP', 'IDP'), ('IDM', 'IDM')], default='IDP', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(to='core.Video'),
        ),
    ]
