# Generated by Django 3.2.12 on 2023-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230816_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Physik', 'Physik'), ('Kunst', 'Kunst')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.CharField(choices=[('Physik', 'Physik'), ('Kunst', 'Kunst')], default='Physik', max_length=10),
            preserve_default=False,
        ),
    ]
