# Generated by Django 3.2.12 on 2023-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20231005_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True),
        ),
    ]
