# Generated by Django 3.2.12 on 2023-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20231010_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studi', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cours',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('1', '1'), ('2', '2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institut',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='group_courses',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('1', '1'), ('2', '2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studierende', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_courses',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('1', '1'), ('2', '2')], default='Willkommen', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], default='Willkommen', max_length=20, null=True),
        ),
    ]
