# Generated by Django 3.2.12 on 2023-10-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_profile_age_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age_limit',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='group_courses',
            new_name='group_cours',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='group_institutes',
            new_name='group_institut',
        ),
    ]
