# Generated by Django 3.2.12 on 2023-10-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20231026_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='group_courses',
        ),
        migrations.AddField(
            model_name='movie',
            name='group_courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
    ]
