# Generated by Django 3.2.12 on 2023-10-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_group_course_profile_group_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='course',
            new_name='courses',
        ),
    ]
