# Generated by Django 3.2.12 on 2023-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_course_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studierende', max_length=20, null=True, verbose_name="User' Status"),
        ),
    ]
