# Generated by Django 3.2.12 on 2023-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studierende', max_length=20, null=True, verbose_name='User Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(related_name='Kurse', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institut',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], default='Willkommen', max_length=20, null=True, verbose_name='Institut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], max_length=20, null=True, verbose_name='Profil Status'),
        ),
    ]
