# Generated by Django 3.2.12 on 2023-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_profile_group_institut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_courses',
            field=models.ManyToManyField(blank=True, null=True, to='core.Course', verbose_name='Kurse'),
        ),
    ]
