# Generated by Django 3.2.12 on 2023-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_courses',
            field=models.ManyToManyField(to='core.Course', verbose_name='Kurse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_institut',
            field=models.CharField(choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, verbose_name='Institut'),
        ),
    ]
