# Generated by Django 3.2.12 on 2023-10-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_profile_group_institut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_courses',
            field=models.ManyToManyField(blank=True, to='core.Course', verbose_name='Kurse'),
        ),
    ]
