# Generated by Django 3.2.12 on 2023-09-26 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], default='Studi', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('IDP', 'IDP'), ('IDM', 'IDM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('IDP', 'IDP'), ('IDM', 'IDM')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], default='Studi', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
