# Generated by Django 3.2.12 on 2023-09-28 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230928_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_institutes',
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.CharField(choices=[('Physik', 'Physik'), ('Kunst', 'Kunst')], default='Physik', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='group_institutes',
            field=models.CharField(choices=[('IDP', 'IDP'), ('IDM', 'IDM')], default='IDP', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
