# Generated by Django 3.2.12 on 2023-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_group_institutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids'), ('Studi', 'Studi'), ('Prof', 'Prof')], default='Studi', max_length=10, null=True),
        ),
    ]
