# Generated by Django 3.2.12 on 2023-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20231023_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studierende', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('Dokumentarfilm', 'Dokumentarfilm'), ('Physik', 'Physik'), ('Mathematik', 'Mathematik'), ('Informatik', 'Informatik'), ('Kunstgeschichte', 'Kunstgeschichte'), ('Chemie', 'Chemie'), ('Biologie', 'Biologie'), ('Wirtschaft', 'Wirtschaft'), ('Literatur', 'Literatur'), ('Geschichte', 'Geschichte')], max_length=20, null=True),
        ),
    ]
