# Generated by Django 3.2.12 on 2023-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20231026_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='group_cours',
            new_name='group_course',
        ),
    ]
