# Generated by Django 3.2.12 on 2023-10-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20231026_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cours',
            new_name='course',
        ),
    ]
