# Generated by Django 3.2.12 on 2023-10-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20231026_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='group_course',
            new_name='group_courses',
        ),
    ]
