# Generated by Django 3.2.12 on 2023-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_profile_group_institut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='group_courses',
            field=models.ManyToManyField(to='core.Course', verbose_name='Kurse'),
        ),
    ]
