# Generated by Django 3.2.12 on 2023-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_movie_group_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='core.Course', verbose_name='Kurse'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(to='core.Profile', verbose_name='Profil'),
        ),
    ]
