# Generated by Django 3.2.12 on 2023-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20231030_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], default='Studierende', max_length=20, null=True, verbose_name='User Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='core.Course', verbose_name='Kurse'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(to='core.Profile', verbose_name='Profile'),
        ),
    ]
