# Generated by Django 3.2.12 on 2023-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20231030_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('Studierende', 'Studierende'), ('Mitarbeiter', 'Mitarbeiter')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('Dokumentarfilm', 'Dokumentarfilm'), ('Physik', 'Physik'), ('Mathematik', 'Mathematik'), ('Informatik', 'Informatik'), ('Kunstgeschichte', 'Kunstgeschichte'), ('Chemie', 'Chemie'), ('Biologie', 'Biologie'), ('Wirtschaft', 'Wirtschaft'), ('Literatur', 'Literatur'), ('Geschichte', 'Geschichte')], max_length=20, null=True, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='group_institutes',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True, verbose_name='Institut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_courses',
            field=models.ManyToManyField(to='core.Course', verbose_name='Kurse'),
        ),
    ]
