# Generated by Django 3.2.12 on 2023-10-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20231030_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_institut',
            field=models.CharField(blank=True, choices=[('Willkommen', 'Willkommen'), ('IDP', 'IDP'), ('IDM', 'IDM')], max_length=20, null=True, verbose_name='Institut'),
        ),
    ]
