# Generated by Django 3.2.12 on 2023-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, default='Willkommen', null=True, to='core.Course', verbose_name='Kurse'),
        ),
    ]
