# Generated by Django 3.2.12 on 2023-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_profile_group_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='group_courses',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='group_institutes',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='group_courses',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='group_institut',
            new_name='institut',
        ),
    ]
