# Generated by Django 3.2.12 on 2023-10-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20231030_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='institute',
            new_name='institut',
        ),
    ]
