# Generated by Django 4.2.7 on 2023-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='core.course', verbose_name='Kurse'),
        ),
    ]
