# Generated by Django 4.2.7 on 2023-12-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_profile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profiles',
        ),
    ]
